services:
  app:
    build:
      context: .
    container_name: dummy_endpoints
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dummy_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: test1234
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: test1234
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: dummy_db_cn
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: dummy_db
    ports:
      - "3308:3306"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data: